# Generated by Django 4.0.3 on 2022-03-15 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20, null=True)),
                ('keterangan', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50, null=True)),
                ('penerbit', models.CharField(max_length=40, null=True)),
                ('penulis', models.CharField(max_length=40, null=True)),
                ('jumlah', models.IntegerField(null=True)),
                ('cover', models.ImageField(null=True, upload_to='cover/')),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('kelompok_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.kelompok')),
            ],
        ),
    ]
